module.exports = {
	env: {
		'browser': true,
		'node': true
	},
	root: true,
	parserOptions: {
		'ecmaVersion': 6
	},
	rules: {
		'no-console': 'error',
		'no-const-assign': 'error',
		'no-debugger': 'error',
		'no-dupe-keys': 'error',
		'no-dupe-args': 'error',
		'no-duplicate-case': 'error',
		'no-empty': ['error', {'allowEmptyCatch': true}],
		'no-empty-character-class': 'error',
		'no-eq-null': 'error',
		'no-eval': 'error',
		'no-ex-assign': 'error',
		'no-extra-parens': 'error',
		'no-extra-semi': 'error',
		'no-floating-decimal': 'error',
		'no-func-assign': 'error',
		'no-inner-declarations': ['error', 'both'],
		'no-var': 'error',
		'no-invalid-regexp': 'error',
		'no-invalid-this': 'error',
		'no-invalid-this': 'error',
		'no-irregular-whitespace': 'error',
		'no-lone-blocks': 'error',
		'no-lonely-if': 'error',
		'no-loop-func': 'warn',
		'no-mixed-spaces-and-tabs': 'error',
		'no-multi-spaces': 'warn',
		'no-multiple-empty-lines': 'warn',
		'no-unsafe-negation': 'error',
		'no-new': 'warn',
		'no-redeclare': 'error',
		'no-trailing-spaces': 'warn',
		'no-this-before-super': 'error',
		'no-throw-literal': 'error',
		'no-undef': 'warn',
		'no-undef-init': 'error',
		'no-unexpected-multiline': 'error',
		'no-unreachable': 'error',
		'no-unused-expressions': 'error',
		'no-unused-vars': ['error', { "vars": "all", "args": "after-used" }],
		'no-use-before-define': 'error',
		'no-useless-call': 'error',
		'no-void': 'error',
		'no-with': 'error',
		'array-bracket-spacing': 'error',
		'brace-style': 'error',
		'camelcase': 'error',
		'comma-dangle': 'error',
		'comma-spacing': 'error',
		'comma-style': 'error',
		'consistent-return': 'error',
		'constructor-super': 'error',
		'curly': 'error',
		'default-case': 'error',
		'eqeqeq': 'error',
		'handle-callback-err': 'error',
		'indent': ['error', 2],
		'key-spacing': ['error', { 'beforeColon': false }],
		'quotes': ['error', 'single'],
		'semi': 'error',
		'semi-spacing': ['error', {'before': false, 'after': true}],
		'keyword-spacing': 'error',
		'use-isnan': 'error',
		'valid-typeof': 'error',
		'wrap-iife': 'error'
	}
}